"""Add valid_from date to OfferContribution

Revision ID: 8bd437e7efe0
Revises: ed8dbde4cf0a
Create Date: 2026-01-22 20:12:44.279786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd437e7efe0'
down_revision: Union[str, None] = 'ed8dbde4cf0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_contributions', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    # Skip color type change - already using enum in database
    # op.alter_column('tempo_days', 'color',
    #            existing_type=sa.VARCHAR(length=10),
    #            type_=sa.Enum('BLUE', 'WHITE', 'RED', name='tempocolor'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip color type change - already using enum in database
    # op.alter_column('tempo_days', 'color',
    #            existing_type=sa.Enum('BLUE', 'WHITE', 'RED', name='tempocolor'),
    #            type_=sa.VARCHAR(length=10),
    #            existing_nullable=False)
    op.drop_column('offer_contributions', 'valid_from')
    # ### end Alembic commands ###
