"""Add power_variants to OfferContribution

Revision ID: ed8dbde4cf0a
Revises: 048bdc8487a5
Create Date: 2026-01-22 20:11:50.712964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed8dbde4cf0a'
down_revision: Union[str, None] = '048bdc8487a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_messages_contribution_id'), table_name='contribution_messages')
    op.alter_column('ecowatt', 'values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_ecowatt_id'), 'ecowatt', ['id'], unique=False)
    op.drop_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', type_='unique')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.alter_column('energy_offers', 'hc_schedules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('energy_providers', 'scraper_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('offer_contributions', sa.Column('power_variants', sa.JSON(), nullable=True))
    op.alter_column('offer_contributions', 'pricing_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('offer_contributions', 'hc_schedules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', type_='unique')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.alter_column('pdls', 'offpeak_hours',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('pdls_usage_point_id_key'), 'pdls', type_='unique')
    op.drop_index(op.f('ix_pdls_usage_point_id'), table_name='pdls')
    op.create_index(op.f('ix_pdls_usage_point_id'), 'pdls', ['usage_point_id'], unique=True)
    op.drop_constraint(op.f('pdls_linked_production_pdl_id_fkey'), 'pdls', type_='foreignkey')
    op.create_foreign_key(None, 'pdls', 'pdls', ['linked_production_pdl_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.drop_constraint(op.f('refresh_tracker_cache_type_key'), 'refresh_tracker', type_='unique')
    op.drop_index(op.f('ix_refresh_tracker_cache_type'), table_name='refresh_tracker')
    op.create_index(op.f('ix_refresh_tracker_cache_type'), 'refresh_tracker', ['cache_type'], unique=True)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    # Skip color type change - already using enum in database
    # op.alter_column('tempo_days', 'color',
    #            existing_type=sa.VARCHAR(length=10),
    #            type_=sa.Enum('BLUE', 'WHITE', 'RED', name='tempocolor'),
    #            existing_nullable=False)
    op.drop_constraint(op.f('tempo_days_date_key'), 'tempo_days', type_='unique')
    op.drop_index(op.f('ix_tempo_days_date'), table_name='tempo_days')
    op.create_index(op.f('ix_tempo_days_date'), 'tempo_days', ['date'], unique=True)
    op.drop_constraint(op.f('users_client_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_client_id_key'), 'users', ['client_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tempo_days_date'), table_name='tempo_days')
    op.create_index(op.f('ix_tempo_days_date'), 'tempo_days', ['date'], unique=False)
    op.create_unique_constraint(op.f('tempo_days_date_key'), 'tempo_days', ['date'], postgresql_nulls_not_distinct=False)
    # Skip color type change - already using enum in database
    # op.alter_column('tempo_days', 'color',
    #            existing_type=sa.Enum('BLUE', 'WHITE', 'RED', name='tempocolor'),
    #            type_=sa.VARCHAR(length=10),
    #            existing_nullable=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_refresh_tracker_cache_type'), table_name='refresh_tracker')
    op.create_index(op.f('ix_refresh_tracker_cache_type'), 'refresh_tracker', ['cache_type'], unique=False)
    op.create_unique_constraint(op.f('refresh_tracker_cache_type_key'), 'refresh_tracker', ['cache_type'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=False)
    op.create_unique_constraint(op.f('permissions_name_key'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'pdls', type_='foreignkey')
    op.create_foreign_key(op.f('pdls_linked_production_pdl_id_fkey'), 'pdls', 'pdls', ['linked_production_pdl_id'], ['id'])
    op.drop_index(op.f('ix_pdls_usage_point_id'), table_name='pdls')
    op.create_index(op.f('ix_pdls_usage_point_id'), 'pdls', ['usage_point_id'], unique=False)
    op.create_unique_constraint(op.f('pdls_usage_point_id_key'), 'pdls', ['usage_point_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('pdls', 'offpeak_hours',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('offer_contributions', 'hc_schedules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('offer_contributions', 'pricing_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('offer_contributions', 'power_variants')
    op.alter_column('energy_providers', 'scraper_urls',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('energy_offers', 'hc_schedules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('email_verification_tokens_token_key'), 'email_verification_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ecowatt_id'), table_name='ecowatt')
    op.alter_column('ecowatt', 'values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_contribution_messages_contribution_id'), 'contribution_messages', ['contribution_id'], unique=False)
    # ### end Alembic commands ###
